all:
  vars:
    ansible_user: ubuntu
  children:
    amx-app:
      children:
        app:
          children:
            swarm_managers: {}
            swarm_workers: {}
    swarm_managers:
      hosts:
        app-amx-01.example.com:
          ansible_host: 10.0.3.10
    swarm_workers:
      hosts:
        app-amx-02.example.com:
          ansible_host: 10.0.3.11
        app-amx-03.example.com:
          ansible_host: 10.0.3.12
